---
- name: create instance groups
  hosts: localhost
  roles:
  - instance-groups

- include: ../../../../../openshift-ansible/playbooks/byo/openshift-cluster/upgrades/{{ openshift_vers }}/upgrade.yml
