---
- name: delete ns records
  gcdns_record:
    record: '{{ item.record }}'
    zone: '{{ public_hosted_zone }}'
    type: '{{ item.type }}'
    overwrite: true
    state: absent
  with_items:
  - record: '{{ openshift_master_cluster_public_hostname }}'
    type: A
  - record: '{{ openshift_master_cluster_hostname }}'
    type: A
  - record: '{{ wildcard_zone }}'
    type: A
  - record: '*.{{ wildcard_zone }}'
    type: CNAME
