---
# Either to checkpoint the dynamic inventory into a static one
refresh_inventory: True
inventory: static
inventory_path: ~/openstack-inventory

# Either to configure bastion
use_bastion: true

# SSH user/key/options to access hosts via bastion
ssh_user: openshift
ssh_options: >-
  -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
  -o ConnectTimeout=90 -o ControlMaster=auto -o ControlPersist=270s
  -o ServerAliveInterval=30 -o GSSAPIAuthentication=no

# SSH key to access nodes
private_ssh_key: ~/.ssh/openshift

# The patch to store the generated config to access bastion/hosts
ssh_config_path: /tmp/ssh.config.ansible
