---
- name: Create haproxy VM on vCenter
  vmware_guest:
    hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: False
    name: "{{ item.value.guestname }}"
    cluster: "{{ vcenter_cluster}}"
    datacenter: "{{ vcenter_datacenter }}"
    resource_pool: "{{ vcenter_resource_pool }}"
    template: "{{vcenter_template_name}}"
    folder: "/{{ vcenter_folder }}"
    annotation: "{{ item.value.tag }}"
    state: poweredon
    wait_for_ip_address: true
    disk:
    - size_gb: 60
      datastore: "{{ vcenter_datastore }}"
      type: thin
    - size_gb: 40
      datastore: "{{ vcenter_datastore }}"
      type: thin
    - size_gb: 40
      datastore: "{{ vcenter_datastore }}"
      type: thin
    networks:
    - name: "{{ vm_network }}"
      ip: "{{ item.value.ip4addr }}"
      netmask: "{{ vm_netmask }}"
      gateway: "{{ vm_gw }}"
    customization:
      domain: "{{dns_zone}}"
      dns_servers:
      - "{{ vm_dns }}"
      dns_suffix: "{{dns_zone}}"
      hostname: "{{ item.value.guestname}}"
  with_dict: "{{host_inventory}}"
  when: "'haproxy' in item.value.guestname"

- name: Add haproxy server to inventory
  add_host: hostname="{{ item.value.guestname}}" ansible_ssh_host="{{ item.value.ip4addr }}" groups="{{ item.value.tag }}, haproxy_group"
  with_dict: "{{ host_inventory }}"
  when: "'haproxy' in item.value.guestname"
