---
env_id: "openshift"
public_dns_domain: "example.com"
public_dns_nameservers: []

openstack_ssh_public_key: "openshift"
openstack_default_image_name: "centos7"
openstack_default_flavor: "m1.medium"
openstack_external_network_name: "public"

openstack_num_masters: 1
openstack_num_infra: 1
openstack_num_nodes: 2

# # Numerical index of nodes to remove
# openstack_nodes_to_remove: []

docker_volume_size: "15"

openstack_subnet_prefix: "192.168.99"

# # Red Hat subscription
rhsm_register: False

# # Using Red Hat Satellite:
#rhsm_register: True
#rhsm_satellite: 'sat-6.example.com'
#rhsm_org: 'OPENSHIFT_ORG'
#rhsm_activationkey: '<activation-key>'

# # Or using RHN username, password and optionally pool:
#rhsm_register: True
#rhsm_username: '<username>'
#rhsm_password: '<password>'
#rhsm_pool: '<pool id>'

#rhsm_repos:
# - "rhel-7-server-rpms"
# - "rhel-7-server-ose-3.5-rpms"
# - "rhel-7-server-extras-rpms"
# - "rhel-7-fast-datapath-rpms"


# # Roll-your-own DNS
#openstack_num_dns: 0
#external_nsupdate_keys:
#  public:
#    key_secret: 'SKqKNdpfk7llKxZ57bbxUnUDobaaJp9t8CjXLJPl+fRI5mPcSBuxTAyvJPa6Y9R7vUg9DwCy/6WTpgLNqnV4Hg=='
#    key_algorithm: 'hmac-md5'
#    server: '192.168.1.1'
#  private:
#    key_secret: 'kVE2bVTgZjrdJipxPhID8BEZmbHD8cExlVPR+zbFpW6la8kL5wpXiwOh8q5AAosXQI5t95UXwq3Inx8QT58duw=='
#    key_algorithm: 'hmac-md5'
#    server: '192.168.1.2'


# NOTE(shadower): Do not change this value. The Ansible user is currently
# hardcoded to `openshift`.
ansible_user: openshift

# # Use a single security group for a cluster (default: false)
#openstack_flat_secgrp: false
