---
- include: stage-vsphere.yaml
  tags: ['setup', 'stage', 'all-vms']

- include: setup-nfs.yaml
  tags: ['nfs', 'all-vms']

- include: prod-ose.yaml
  tags: ['prod', 'all-vms']

- include: setup-haproxy.yaml
  tags: ['haproxy', 'all-vms']

- include: openshift-install.yaml
  tags: ['ocp-install', 'all-ocp']

- include: openshift-configure.yaml
  tags: ['ocp-configure', 'all-ocp']

- include: ../../../playbooks/post-validation.yaml
  tags: ['ocp-demo', 'all-ocp']

- include: openshift-minor-upgrade.yaml
  tags: ['ocp-update']

- include: cleanup-vsphere.yaml
  tags: ['clean']
