---
- hosts: localhost
  vars_files:
    - vars/main.yaml
  roles:
    - create-vm-nfs

- name: Deploy NFS server
  hosts: nfs_group
  vars_files:
    - vars/main.yaml
  roles:
    - rhel_subscribe
    - vmware-guest-setup
    - nfs-server
  ignore_errors: yes
