---
- hosts: localhost
  gather_facts: yes
  become: no
  pre_tasks:
  - name: set fact
    set_fact:
      openshift_master_cluster_public_hostname: "{{ openshift_master_cluster_public_hostname }}"
  - name: set fact
    set_fact:
      openshift_master_cluster_hostname: "{{ openshift_master_cluster_hostname }}"
  - name: set fact
    set_fact:
      console_port: "{{ console_port}}"
  - name: set fact
    set_fact:
      wildcard_zone: "{{app_dns_prefix}}.{{public_hosted_zone}}"
  roles:
  # Group systems
  - instance-groups
  - validate-public

- hosts: masters
  gather_facts: no
  roles:
  - validate-masters

- hosts: masters
  gather_facts: yes
  roles:
  - validate-etcd

- hosts: single_master
  gather_facts: yes
  become: yes
  roles:
  - validate-app
