#cloud-config
cloud_config_modules:
- disk_setup
- mounts

fs_setup:
- label: emptydir
  filesystem: xfs
  device: /dev/xvdc
  partition: auto

runcmd:
- mkdir -p /var/lib/origin/openshift.local.volumes

mounts:
- [ /dev/xvdc, /var/lib/origin/openshift.local.volumes, xfs, "defaults,gquota" ]

write_files:
- content: |
    DEVS='/dev/xvdb'
    VG=docker_vol
    DATA_SIZE=95%VG
    STORAGE_DRIVER=overlay2
    ROOT_SIZE=45G
    GROWPART=true
  path: /etc/sysconfig/docker-storage-setup
  owner: root:root

users:
- default

system_info:
  default_user:
    name: ec2-user

